In [1]:
pwd

'/work/Pandas'

In [2]:
import pandas as pd
import numpy as np

## `pd.DataFrame()`

### Numpy Arrayから作成

In [3]:
ndarray1 = np.arange(10).reshape(2, 5)
print(ndarray1)
type(ndarray1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


numpy.ndarray

In [4]:
ndarray2 = np.linspace(0, 9, num=10).reshape(2, 5)
print(ndarray2)
type(ndarray2)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


numpy.ndarray

In [5]:
pd.DataFrame(ndarray1)

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [6]:
pd.DataFrame(ndarray2)

0    1    2    3    4
0  0.0  1.0  2.0  3.0  4.0
1  5.0  6.0  7.0  8.0  9.0

In [7]:
pd.DataFrame(ndarray1, 
            index = ['index1', 'index2'], 
            columns = ['a', 'b', 'c', 'd', 'e'])

a  b  c  d  e
index1  0  1  2  3  4
index2  5  6  7  8  9

### Dictionaryから作成

In [8]:
data1 = {
    'name': 'John',
    'sex': 'male',
    'age': 22
}
data2 = {
    'name': 'Zack',
    'sex': 'male',
    'age': 30
}
data3 = {
    'name': 'Emily',
    'sex': 'female',
    'age': 32
}
pd.DataFrame([data1, data2, data3])

name     sex  age
0   John    male   22
1   Zack    male   30
2  Emily  female   32

In [9]:
# more easier

data = {
    'name': ['John', 'Zack', 'Emily'], 
    'sex': ['male', 'male', 'female'], 
    'age': [22, 30, 32]
}
df = pd.DataFrame(data)

In [10]:
df

name     sex  age
0   John    male   22
1   Zack    male   30
2  Emily  female   32

### csvファイルから作成

In [11]:
df = pd.read_csv('movie_dataset/tmdb_5000_movies.csv')

In [12]:
df

budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4     [{"id": 818, "name": "based on novel"}, {"id":...                en   
...                                                 ...               ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...                es   
4799                                                 []                en   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en   
4801                                                 []                en   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ... 

In [13]:
len(df)

4803

In [14]:
# カラムを省略せずに表示
# pd.set_option('display.max_columns', None)

# rowを省略せずに表示
# pd.set_option('display.max_rows', None)

In [15]:
df.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [16]:
# 統計量を確認

df.describe()

budget             id   popularity       revenue      runtime  \
count  4.803000e+03    4803.000000  4803.000000  4.803000e+03  4801.000000   
mean   2.904504e+07   57165.484281    21.492301  8.226064e+07   106.875859   
std    4.072239e+07   88694.614033    31.816650  1.628571e+08    22.611935   
min    0.000000e+00       5.000000     0.000000  0.000000e+00     0.000000   
25%    7.900000e+05    9014.500000     4.668070  0.000000e+00    94.000000   
50%    1.500000e+07   14629.000000    12.921594  1.917000e+07   103.000000   
75%    4.000000e+07   58610.500000    28.313505  9.291719e+07   118.000000   
max    3.800000e+08  459488.000000   875.581305  2.787965e+09   338.000000   

       vote_average    vote_count  
count   4803.000000   4803.000000  
mean       6.092172    690.217989  
std        1.194612   1234.585891  
min        0.000000      0.000000  
25%        5.600000     54.000000  
50%        6.200000    235.000000  
75%        6.800000    737.000000  
max       10.000000  13752.000000

In [17]:
# columnsの中身を確認

df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [18]:
# 各columnsの中身を確認
# Stringsで渡してあげると、Seriesで返してくれる

df['revenue']

0       2787965087
1        961000000
2        880674609
3       1084939099
4        284139100
           ...    
4798       2040920
4799             0
4800             0
4801             0
4802             0
Name: revenue, Length: 4803, dtype: int64

In [19]:
# 複数のcolumnsの中身を確認
# Listで渡してあげると、DataFrameで返してくれる

df[['budget', 'revenue', 'release_date']]

budget     revenue release_date
0     237000000  2787965087   2009-12-10
1     300000000   961000000   2007-05-19
2     245000000   880674609   2015-10-26
3     250000000  1084939099   2012-07-16
4     260000000   284139100   2012-03-07
...         ...         ...          ...
4798     220000     2040920   1992-09-04
4799       9000           0   2011-12-26
4800          0           0   2013-10-13
4801          0           0   2012-05-03
4802          0           0   2005-08-05

[4803 rows x 3 columns]

In [20]:
# index指定してデータを取ってくる

df.iloc[10:13]

budget                                             genres  \
10  270000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
11  200000000  [{"id": 12, "name": "Adventure"}, {"id": 28, "...   
12  200000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                             homepage     id  \
10                            http://www.superman.com   1452   
11  http://www.mgm.com/view/movie/234/Quantum-of-S...  10764   
12       http://disney.go.com/disneypictures/pirates/     58   

                                             keywords original_language  \
10  [{"id": 83, "name": "saving the world"}, {"id"...                en   
11  [{"id": 627, "name": "killing"}, {"id": 1568, ...                en   
12  [{"id": 616, "name": "witch"}, {"id": 663, "na...                en   

                                original_title  \
10                            Superman Returns   
11                           Quantum of Solace   
12  Pirates of the Caribbean: Dead Man's Chest   

                                             overview  popularity  \
10  Superman returns to discover his 5-year absenc...   57.925623   
11  Quantum of Solace continues the adventures of ...  107.928811   
12  Captain Jack Sparrow works his way out of a bl...  145.847379   

                                 production_companies  \
10  [{"name": "DC Comics", "id": 429}, {"name": "L...   
11          [{"name": "Eon Productions", "id": 7576}]   
12  [{"name": "Walt Disney Pictures", "id": 2}, {"...   

                                 production_countries release_date  \
10  [{"iso_3166_1": "US", "name": "United States o...   2006-06-28   
11  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2008-10-30   
12  [{"iso_3166_1": "JM", "name": "Jamaica"}, {"is...   2006-06-20   

       revenue  runtime                                   spoken_languages  \
10   391081192    154.0  [{"iso_639_1": "en", "name": "English"}, {"iso...   
11   586090727    106.0  [{"iso_639_1": "en", "name": "English"}, {"iso...   
12  1065659812    151.0  [{"iso_639_1": "en", "name": "English"}, {"iso...   

      status                                        tagline  \
10  Released                                            NaN   
11  Released  For love, for hate, for justice, for revenge.   
12  Released                                  Jack is back!   

                                         title  vote_average  vote_count  
10                            Superman Returns           5.4        1400  
11                           Quantum of Solace           6.1        2965  
12  Pirates of the Caribbean: Dead Man's Chest           7.0        5246

In [21]:
# index指定して、columnsを指定すると、対象のデータを取ってくる

df.iloc[10:13]['budget']# StringsだとSeries

10    270000000
11    200000000
12    200000000
Name: budget, dtype: int64

In [22]:
# index指定して、columnsを指定すると、対象のデータを取ってくる,その２

df.iloc[10:13][['budget']]# ListだとDataFrame

budget
10  270000000
11  200000000
12  200000000

In [23]:
# 稀なケース
# indexがStringsで、columnsが数字の場合

columns = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

array = np.arange(25).reshape(5, 5)

df = pd.DataFrame(array, index=index, columns=columns)

In [24]:
df

1   2   3   4   5
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24

In [25]:
df.loc['c']

1    10
2    11
3    12
4    13
5    14
Name: c, dtype: int64

In [26]:
data = {
    'name': ['John', 'Zack', 'Emily'], 
    'sex': ['male', 'male', 'female'], 
    'age': [22, 30, 32]
}
df = pd.DataFrame(data)

In [27]:
df

name     sex  age
0   John    male   22
1   Zack    male   30
2  Emily  female   32

In [28]:
# 新しいcolumnsを追加する

df['cost'] = [100, 200, 300]

In [29]:
df

name     sex  age  cost
0   John    male   22   100
1   Zack    male   30   200
2  Emily  female   32   300

In [30]:
# 特定のindexやcolumnsを削る

df.drop(0)# index除去

name     sex  age  cost
1   Zack    male   30   200
2  Emily  female   32   300

In [31]:
df.drop('name', axis=1)# columns除去

sex  age  cost
0    male   22   100
1    male   30   200
2  female   32   300

In [32]:
# inplace=Trueでオリジナルデータの該当データも除去

df.drop('name', axis=1, inplace=True)

In [33]:
df

sex  age  cost
0    male   22   100
1    male   30   200
2  female   32   300

In [34]:
# more easier

df = df.drop(2)# index除去

In [35]:
df

sex  age  cost
0  male   22   100
1  male   30   200

In [36]:
# more easier

df = df.drop('sex', axis=1)# columns除去

In [37]:
df

age  cost
0   22   100
1   30   200