In [1]:
import numpy as np

In [2]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
# 普通のリストで同じことをしても計算はされないで、
# 結合だけされる
a = [1, 2, 3]
b = [1, 2, 3]

In [6]:
a + b

[1, 2, 3, 1, 2, 3]

In [7]:
# ブロードキャストが起きて足りない配列を補ってくれている
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [10]:
# 実際には上記の行列計算は、下記の行列計算を行っていることと同じ
# ブロードキャストが起きて足りない配列を補ってくれている
array1 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [11]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [13]:
array2 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])