In [1]:
import numpy as np

In [4]:
ndarray1 = np.array([[1, 2], [3, 4], [5, 6]])

In [5]:
print(ndarray)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
print(ndarray[-1, 1])# []内にまとめて書くのが一般的

6


In [10]:
ndarray2 = np.array([1, 2, 3, 4])
# [0], [1], [2], [3]
# [-4], [-3], [-2], [-1]

In [12]:
ndarray2[1:3]# [1]以上[3]未満

array([2, 3])

In [17]:
ndarray2[2:]# [2]以上

array([3, 4])

In [19]:
ndarray2[:2]# [2]未満

array([1, 2])

In [27]:
ndarray2 = np.array([1, 2, 3, 4])
# [0], [1], [2], [3]
# [-4], [-3], [-2], [-1]

In [28]:
ndarray2[-2:]# [-2]以上

array([3, 4])

In [29]:
ndarray2[:-2]# [-2]未満

array([1, 2])

In [30]:
ndarray2[-3:-1]# [-3]以上[-1]未満、[-1:-3]の書き方では値は返してくれない

array([2, 3])

In [31]:
array3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [35]:
array3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
array3.shape

(4, 4)

In [37]:
array3[:3, 2:]# [行3行未満, 列2列以上]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [38]:
# 上記と似ているがスライシング結果は異なるので書き方に注意
array3[:3][2:]# [行3行目未満][更に行2行目以上]

array([[ 9, 10, 11, 12]])