# 数学で使う便利関数

In [3]:
import numpy as np

## 平方根（square root）

In [4]:
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

## log(logarithm)

In [6]:
x = np.linspace(1, 10, 10)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [8]:
np.log2(x)# log2 version

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809])

In [9]:
np.log10(x)# log10 verson

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

## 指数関数（exponential function)

In [10]:
np.exp(1)# e**1(ネイピア数)

2.718281828459045

In [11]:
np.e# ネイピア数

2.718281828459045

## 合計(summation)

In [12]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.sum(array)

55

In [16]:
ndarray = array.reshape(2, 5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
np.sum(ndarray, axis=1)# 行毎

array([15, 40])

## 絶対値（absolute value）

In [25]:
array = np.arange(-10, 0)
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [26]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])