In [1]:
import numpy as np

In [40]:
np.random.seed(1)
std_norm = np.random.randn(5, 5)
std_norm

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595]])

In [6]:
# 最大値

std_norm.max()

2.4098005835822134

In [7]:
# 最大値その２
np.max(std_norm)

2.4098005835822134

In [8]:
# 最小値

std_norm.min()

-2.6302770053602043

In [10]:
# 最大値のインデックスを取得

std_norm.argmax()

20

In [11]:
# 最大値その３

std_norm.flatten()[20]# 一次元配列にした時の２０番目の要素

2.4098005835822134

In [12]:
# 最小値のインデックスを取得

std_norm.argmin()

6

In [13]:
# 上記の検算

std_norm.flatten()[6]# 一次元配列にした時の6番目の要素

-2.6302770053602043

In [14]:
# 平均を取得

std_norm.mean()

-0.06928913384653738

In [15]:
# 中央値を取得
# 書き方がmax, minと違うので注意

np.median(std_norm)

-0.12426687148245873

**中央値(median)は平均値(mean)よりも計算に時間がかかるが、
外れ値の影響を受けにくい**

In [32]:
# median vs mean

a = np.random.randn(1000, 1000)

import time

before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()

median = after_median - before
mean = after_mean - after_median
print('median:{:.5f}sec'.format(median))
print('mean:{:.5f}sec'.format(mean))
print('median-mean:{:.5f}sec'.format(median - mean))

median:0.01281sec
mean:0.00061sec
median-mean:0.01219sec


**標準偏差**

正規分布内において、平均との差を二乗した合計を、データ数で割った正の平方根。

[資料１](https://i.gyazo.com/692653c7165c145f2660db74b59ad148.png)

In [33]:
# 標準偏差を取得

np.std(std_norm)

1.1356099247332687

### 補足

`~.max(axis=0)`や`~.min(axis=1)`で列や行ごとの最大値、最小値を取ってくることができる。

In [41]:
np.random.seed(1)
std_norm = np.random.randn(5, 5)
std_norm

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595]])

In [42]:
std_norm.max(axis=0)# 列毎

array([1.62434536, 1.74481176, 0.90159072, 0.50249434, 1.13376944])

In [43]:
std_norm.min(axis=1)# 行毎

array([-1.07296862, -2.3015387 , -2.06014071, -1.09989127, -1.10061918])