In [1]:
import numpy as np

### `np.random.rand()`

In [2]:
np.random.rand()

0.8486153867767512

In [4]:
# 擬似関数(pseudo random)

np.random.rand(3, 4)

array([[0.76239465, 0.59984212, 0.00823759, 0.33883822],
       [0.67323511, 0.66692102, 0.48193196, 0.64875425],
       [0.91241499, 0.74906706, 0.27574746, 0.61887167]])

### `np.random.seed()`

seedを指定すると、毎回同じ乱数を精製してくれる。

**乱数を生成するときはなるべくseedを使う。**

In [8]:
np.random.seed(1)
np.random.rand()

0.417022004702574

### `np.random.randn()`

平均が０、分散が１の時の標準正規分布からランダムに値を取ってくる

In [9]:
np.random.randn()

-0.8021728386486427

### `np.random.randn()`

任意の平均と標準偏差の正規分布から擬似乱数を生成

In [10]:
np.random.normal(0, 1)# 上のrandnと同じで、平均が０で、分散が１

-0.4488778077207725

### `np.random.randint()`

low以上high未満のランダムな整数でsizeのndarrayを生成

In [12]:
# 10〜100までの整数で、２行３列の行列を返す

np.random.randint(10, 100, (2, 3))

array([[26, 11, 86],
       [81, 16, 35]])

In [14]:
np.random.randint(10)# 10未満の整数をランダムで返してくれる

4

### `np.random.choice()`

指定されたndarrayからランダムな値を取ってくる

In [15]:
a = [1, 2, 3]

np.random.choice(a)

3

In [20]:
example = np.arange(1, 10, 2)
example

array([1, 3, 5, 7, 9])

In [25]:
idx = np.random.choice(example)
idx

3