# Shape

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [4]:
array1 = np.array([1, 2])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
# shapeがあっていないとブロードキャストはされない
array1 + array2

ValueError: operands could not be broadcast together with shapes (2,) (3,3) 

In [6]:
array1 = np.array([[1, 2], [3, 4], [5, 6]])

In [7]:
# 形を調べる
array1.shape

(3, 2)

In [8]:
# 形を変える
array1.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 似ているけど非なるベクトルと一次元行列
array1 = np.array([1, 2 ,3])
array2 = np.array([[1, 2, 3]])

In [10]:
# ベクトル
print(array1)
print(array1.shape)# 次元という概念は存在していない

[1 2 3]
(3,)


In [11]:
# 二次元配列
# 次元数のことをrankと呼ぶ
print(array2)
print(array2.shape)# 次元という概念な存在している

[[1 2 3]]
(1, 3)


In [12]:
# rankを増やす
# ベクトルを二次元配列に変換
# axis=0は行方向で、0番目の要素として増えると覚えると分かり易い
array3 = np.expand_dims(array1, axis=0)

In [13]:
print(array3)
print(array3.shape)# (1, 3)で３の前の0番目が増えている

[[1 2 3]]
(1, 3)


In [14]:
# axis=1は列方向で、1番目の要素として増えると覚えると分かり易い
array4 = np.expand_dims(array1, axis=1)

In [15]:
print(array4)
print(array4.shape)# (1, 3)で３の後の１番目が増えている

[[1]
 [2]
 [3]]
(3, 1)


squeezeは少ない方の次元を減らす

In [16]:
# rankを1つ減らす
array5 = np.squeeze(array3)

In [17]:
print(array5)
print(array5.shape)

[1 2 3]
(3,)


In [18]:
# rankを1つ減らす
array6 = np.squeeze(array4)

In [19]:
print(array6)
print(array6.shape)

[1 2 3]
(3,)


In [20]:
array7 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])

In [21]:
print(array7)
print(array7.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [27]:
# rankを強制的に１（一次元）にする
array8 = array7.flatten()

In [28]:
print(array8)
print(array8.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
