# Numpy

In [1]:
import numpy as np

In [2]:
# 今回呼んだnumpyファイルの参照元
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## Numpy Arrays

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
matrix[0]

array([1, 2, 3])

In [6]:
matrix[0][0]

1

Numpyの数字はデータ型が普通にintgerじゃないので注意！

In [7]:
type(matrix[0][0])

numpy.int64

In [12]:
# dtype=でデータ型を指定できる
# 良く使うデータ型その１：unit8
ndarray1 = np.array([1, 2, 3], dtype=np.uint8)

In [13]:
ndarray1

array([1, 2, 3], dtype=uint8)

In [15]:
# 良く使うデータ型その2：float32
# 機械学習ではデータを保存する際に良く使う
ndarray2 = np.array([1, 2, 3], dtype=np.float32)

In [16]:
ndarray2

array([1., 2., 3.], dtype=float32)

In [17]:
# 良く使うデータ型その3：float64
# 機械学習ではモデル学習をする際に良く使う
ndarray3 = np.array([1, 2, 3], dtype=np.float64)

In [18]:
ndarray3

array([1., 2., 3.])

In [22]:
# データ型の変換
ndarray3.astype(np.uint8)

array([1, 2, 3], dtype=uint8)