In [2]:
import numpy as np

### `np.clip()`

`np.clip(a, a_min, a_max)`

最小値と最大値を設定する。

それらの範囲以外の数字はその配列の最小値、もしくは最大値が適用される。

In [3]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

### `np.where()`

where(condition, [x, y])

**Returns**

out : ndarray

An array with elements from `x` where `condition` is **True**, and elements from `y` where `condition` is *False*.

In [9]:
# filterとして使用する場合

array[array > 3]

array([4, 5, 6, 7, 8, 9])

In [10]:
# filterとして使用する場合
# Tupleで返ってくる為、一般的にfilterとしては使用しない

np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)


In [6]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [11]:
np.where(array < 5, array, 10*array)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [12]:
ndarray = array.reshape(2, 5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# 元の配列が二次元でも、一次元で返ってくるので注意

ndarray[ndarray > 3]

array([4, 5, 6, 7, 8, 9])

In [15]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [16]:
# 全てがTrueかどうか

(ndarray > 3).all()

False

In [17]:
# 一つでもTrueが含まれているかどうか

(ndarray > 3).any()

True

In [18]:
# axis=0 or 1の形で指定可能

(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

### `np.unique()`

In [19]:
array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5])

In [20]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [21]:
np.unique(array, return_counts=True)# return_countsは各要素の数

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 2, 3]))

### `np.bincount()`

各要素の連番の数を数えてくれる

In [22]:
np.bincount(array)

array([0, 1, 2, 3, 2, 3])

### `np.concatenate()`

In [24]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [26]:
ndarray_odd = np.arange(1, 18, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [27]:
np.concatenate([ndarray_even, ndarray_odd])# defaultがaxis=0

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [28]:
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

### `np.stack()`

指定したaxisに対してrankを一つ増やしてくれる

In [48]:
np.stack([ndarray_even, ndarray_odd], axis=0)

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [49]:
stack_array = _# _で最後に出力した戻り値が返される

In [50]:
stack_array.shape

(2, 3, 3)

In [51]:
np.stack([ndarray_even, ndarray_odd], axis=1)

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]],

       [[12, 14, 16],
        [13, 15, 17]]])

In [52]:
stack_array1 = _# _で最後に出力した戻り値が返される

In [53]:
stack_array1.shape

(3, 2, 3)

In [57]:
np.stack([ndarray_even, ndarray_odd], axis=-1)# axis=2でもOK

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [58]:
stack_array2 = _# _で最後に出力した戻り値が返される

In [60]:
stack_array2.shape

(3, 3, 2)

### `np.transpose()`

転置をしてくれる

In [67]:
np.random.seed(1)
ndarray = np.random.randn(3, 4)
ndarray

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038,  1.46210794, -2.06014071]])

In [69]:
transpose_ndarray = _

In [73]:
transpose_ndarray.shape

(3, 4)

In [74]:
np.transpose(ndarray)

array([[ 1.62434536,  0.86540763,  0.3190391 ],
       [-0.61175641, -2.3015387 , -0.24937038],
       [-0.52817175,  1.74481176,  1.46210794],
       [-1.07296862, -0.7612069 , -2.06014071]])

In [75]:
# np.transposeを簡単に書いた場合

ndarray.T

array([[ 1.62434536,  0.86540763,  0.3190391 ],
       [-0.61175641, -2.3015387 , -0.24937038],
       [-0.52817175,  1.74481176,  1.46210794],
       [-1.07296862, -0.7612069 , -2.06014071]])