In [1]:
import numpy as np

In [5]:
np.arange(1, 15, 4)# ([start], stop, [step])

array([ 1,  5,  9, 13])

In [7]:
# 降順の場合は範囲指定の数を反対側から書く
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

### np.linspace

`np.linspace(start, stop, num=50)`

start以上stop以下の数をnum個で区切った値を出力

stopの数も範囲に含まれるので注意

In [9]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### np.logspace

`np.logspace`(start, stop, num=50)

10**（累乗）start以上10**（累乗）stop以下の数をnum個で区切った数を出力

In [12]:
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

10 ** 0から10 ** 3までの数を累乗で10個取ってくる。

0乗から3乗までを10等分した累乗の数

[10 ** 0/10(0), 10 ** 3/10(0.3), 10 ** 3/5(0.6), 10 ** 9/10(0.9)... 10 ** 30/10(3)]

In [16]:
# 最後の数字を含まない場合

np.linspace(0, 3, 10, endpoint=False)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [17]:
np.logspace(0, 3, 10, endpoint=False)

array([  1.        ,   1.99526231,   3.98107171,   7.94328235,
        15.84893192,  31.6227766 ,  63.09573445, 125.89254118,
       251.18864315, 501.18723363])